import {useEffect,useRef,useState} from "react";
import type {PublicServicePortalQuestion} from "../contracts/questions.js";
import {keywordCategoryLabel} from "../contracts/keyword-categories.js";
import {captureWorkspaceRestOperation} from "./runtime-host.js";

type ManualInput={companyName:string;materials:string;questionGoal:string;perCategory:number};
type Generation={taskId:string;contextToken:string;manualInput:ManualInput};
const emptyInput:ManualInput={companyName:"",materials:"",questionGoal:"",perCategory:1};
export function QuestionGenerationPanel({preview=false,workspaceId,candidates,onUpdate}:{preview?:boolean;workspaceId:string;candidates:PublicServicePortalQuestion[];onUpdate():Promise<unknown>}) {
 const storageKey=`frontmind:intent-generation:${workspaceId}`;
 const [job,setJob]=useState<Generation|null>(()=>{if(preview)return null;try{return JSON.parse(sessionStorage.getItem(storageKey)||"null");}catch{return null;}});
 const [input,setInput]=useState<ManualInput>(job?.manualInput??emptyInput);
 const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [status,setStatus]=useState(job?"已恢复正在生成的问题任务":"");
 const taskRef=useRef(job);taskRef.current=job;
 const post=async (path:string,body:unknown)=>{const response=await captureWorkspaceRestOperation().fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error?.message??`请求失败（${response.status}）`);return data;};
 useEffect(()=>{if(preview)return;if(job)sessionStorage.setItem(storageKey,JSON.stringify(job));else sessionStorage.removeItem(storageKey);},[job,storageKey,preview]);
 useEffect(()=>{if(!job||preview)return;let active=true;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const result=await post("/api/brand-question-portfolio/sync",{taskId:job.taskId,contextToken:job.contextToken,manualInput:job.manualInput});if(!active)return;if(result.status==="ready"){setJob(null);setStatus("候选问题已保存，选择需要的问题加入优化清单。");await onUpdate();}else{setStatus("正在生成候选问题，可以刷新后继续查看。");timer=setTimeout(poll,5000);}}catch(cause){if(active){setError(cause instanceof Error?cause.message:String(cause));setStatus("任务信息已保留，可以刷新后恢复。");}}};timer=setTimeout(poll,2500);return()=>{active=false;clearTimeout(timer);};},[job?.taskId,preview]);
 const start=async()=>{if(busy||job||preview)return;setBusy(true);setError("");try{const result=await post("/api/brand-question-portfolio/start",{manualInput:input});if(!result.task?.id||!result.contextToken)throw new Error("任务响应缺少标识，请先刷新恢复，勿重复创建");setJob({taskId:result.task.id,contextToken:result.contextToken,manualInput:input});setStatus("已开始生成候选问题");}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}finally{setBusy(false);}};
 const select=async(question:PublicServicePortalQuestion)=>{if(preview)return;setBusy(true);setError("");try{await post("/api/intent/questions",{questionId:question.id,expectedRevision:question.revision});await onUpdate();}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}finally{setBusy(false);}};
 return <details className="intent-generation"><summary>从企业信息和参考材料生成问题</summary><p>自行提供企业事实与问题目标；生成过程只使用本轮输入，不要求先建立知识库。</p><div className="intent-generation-form"><label>企业名称<input value={input.companyName} disabled={Boolean(job)} onChange={event=>setInput({...input,companyName:event.target.value})}/></label><label>企业信息和参考材料<textarea rows={5} value={input.materials} disabled={Boolean(job)} placeholder="粘贴企业介绍、产品资料、案例事实或其他参考材料" onChange={event=>setInput({...input,materials:event.target.value})}/></label><label>问题目标<textarea rows={2} value={input.questionGoal} disabled={Boolean(job)} onChange={event=>setInput({...input,questionGoal:event.target.value})}/></label><label>每类选题目标<input type="number" min={1} max={10} value={input.perCategory} disabled={Boolean(job)} onChange={event=>setInput({...input,perCategory:Number(event.target.value)})}/><small>每类生成目标数量的 3 倍候选，方便选择。</small></label><button disabled={preview||busy||Boolean(job)||input.companyName.trim().length<2||input.materials.trim().length<20} onClick={()=>void start()}>{job?"正在生成…":busy?"提交中…":"生成候选问题"}</button>{preview&&<small>本地预览不发起真实生成。</small>}</div>{status&&<p role="status">{status}</p>}{error&&<p role="alert">{error}</p>}{candidates.length>0&&<div className="intent-candidates"><h3>待选候选问题</h3>{candidates.map(question=><article key={question.id}><div><strong>{question.question}</strong><p>{keywordCategoryLabel(question.category)} · {question.intent}</p><small>{question.rationale}</small></div><button disabled={busy||preview} onClick={()=>void select(question)}>加入优化清单</button></article>)}</div>}</details>;
}
